version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: Todo
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"  # Exposes MySQL port 3306 on the host

  web:
    build: .
    ports:
      - "8000:8000"  # Maps host port 8000 to container port 8000
    links:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: Todo
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    volumes:
      - ./vendor:/app/vendor  # Binds the host's ./vendor directory to /app/vendor in the container

volumes:
  db-data:  # Defines a named volume for persisting MySQL data
