---
- name: Update hosts
  hosts: localhost
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    region_name: eu-west-3
    instance_name: myapp-instance
    ansible_user: "ubuntu"
    ansible_ssh_private_key_file: "../ec2keyspem.pem"
  tasks: 
    - name: Retrieve public IP using AWS CLI
      command: "aws ec2 describe-instances --region {{ region_name }} --filters 'Name=tag:Name,Values={{ instance_name }}' --query 'Reservations[*].Instances[*].PublicIpAddress' --output text"
      register: publicIP

    - name: Update the host file
      lineinfile: 
        dest: ./hosts
        line: "{{ publicIP.stdout }} ansible_user={{ ansible_user }} ansible_ssh_private_key_file={{ ansible_ssh_private_key_file }}"
        insertafter: EOF
